### PR TITLE
added macros for faster setup

### PR DESCRIPTION
**Pull request by robrobbins**

### CODE REVIEW

**Comment by robrobbins** [comment]
start with the new alias:

screenshot from 2018-08-08 15-04-15

**Comment by robrobbins** [comment]
users no longer start with any funds:

screenshot from 2018-08-08 15-04-34

**Comment by robrobbins** [comment]
you fund them with `transfer`, note the args are `([userN,...], amount)`

screenshot from 2018-08-08 15-04-59

**Comment by robrobbins** [comment]
then they have monies:

screenshot from 2018-08-08 15-05-15

**Comment by robrobbins** [comment]
approve spending-on-behalf with `approve`. note the args `([contractAddress,...], amount, user)`

screenshot from 2018-08-08 15-05-47

**Comment by robrobbins** [comment]
voting and reg can now spend on the behalf of admin:

screenshot from 2018-08-08 15-06-04

**Comment by robrobbins** [comment]
note that the `approve` function can also take an array of users at arg #3:

**Comment by robrobbins** [comment]
note that `approve` can also take an array of users at arg #3:

screenshot from 2018-08-08 15-06-16

**Comment by robrobbins** [comment]
so:

screenshot from 2018-08-08 15-06-29

**Review by rbharath — APPROVED** [review]
LGTM

**Pull request merged**
